
import { Node, Edge } from '@xyflow/react';

export enum NodeType {
  INPUT = 'inputNode',
  PROCESSOR = 'processorNode',
  IMAGE_GEN = 'imageGenNode',
  DISPLAY = 'displayNode'
}

export enum NodeStatus {
  IDLE = 'idle',
  RUNNING = 'running',
  SUCCESS = 'success',
  ERROR = 'error'
}

export interface BaseNodeData extends Record<string, unknown> {
  label?: string;
  status: NodeStatus;
  errorMessage?: string;
  onConnectClick?: (nodeId: string, screenPos: { x: number, y: number }) => void;
}

export interface InputNodeData extends BaseNodeData {
  inputType: 'text' | 'file' | 'url' | 'mixed';
  value: string;
  // Extended fields for multi-modal input
  textValue?: string;
  urlValue?: string;
  fileContent?: string;
  fileName?: string;
}

export interface ProcessorNodeData extends BaseNodeData {
  systemInstruction: string;
  inputData?: string; // Data received from previous node
  outputData?: string; // Data generated by LLM
}

export interface ImageGenNodeData extends BaseNodeData {
  prompt: string;
  aspectRatio: string;
  generatedImage?: string; // Base64 string of the generated image
  inputData?: string; // Context received from previous node
}

export interface DisplayNodeData extends BaseNodeData {
  content: string;
  contentType: 'markdown' | 'html' | 'text';
}

export interface WorkflowHistory {
  id: string;
  timestamp: number;
  nodes: Node[];
  edges: Edge[];
}
